// src/app/components/project-detail/project-detail.component.ts
import { Component, Input } from '@angular/core';
import { VideoListComponent } from '../video-list/video-list.component';
import { PictureListComponent } from '../picture-list/picture-list.component';
import type { TypeImage, TypeVideo } from '../../../projects';

@Component({
  selector: 'app-project-detail',
  imports: [VideoListComponent, PictureListComponent],
  templateUrl: './project-detail.component.html',
  styleUrl: './project-detail.component.scss',
})
export class ProjectDetailComponent {
  @Input({ required: true }) public description!: string;
  @Input({ required: true }) public videos!: TypeVideo[];
  @Input({ required: true }) public images!: TypeImage[];
}

<div class="project-detail">
  @if (description) {
    <div class="project-detail__item">
      <div class="project-detail__description" [innerHTML]="description"></div>
    </div>
  }
  @if (videos.length) {
    <div class="project-detail__item">
      <app-video-list [videos]="videos"></app-video-list>
    </div>
  }
  @if (images.length) {
    <div class="project-detail__item">
      <app-picture-list [images]="images"></app-picture-list>
    </div>
  }
</div>

// src/Yulianna/components/ProjectDetail.vue
<template>
  <div class="project-detail">
    <div v-if="description" class="project-detail__item">
      <div class="project-detail__description" v-html="description"></div>
    </div>
    <video-list class="project-detail__item" :videos="videos"></video-list>
    <picture-list class="project-detail__item" :images="images"></picture-list>
  </div>
</template>

<script>
import VideoList from './multimedia/VideoList.vue';
import PictureList from './multimedia/PictureList.vue';

export default {
  props: {
    description: {
      type: String,
      default: '',
    },
    videos: {
      type: Array,
      default: () => [],
    },
    images: {
      type: Array,
      default: () => [],
    },
  },
  components: {
    VideoList,
    PictureList,
  },
  name: 'project-detail',
};
</script>

<style lang="stylus">
.project-detail
  margin 40px 0
  &__item + &__item
    margin-top 20px
  &__description
    font-size 20px
</style>
