// src/app/components/footer-content/footer-content.component.ts
import { Component } from '@angular/core';
import { UiCardComponent } from '../ui-card/ui-card.component';

type Item = {
  name: string;
  link: string;
};

@Component({
  selector: 'app-footer-content',
  standalone: true,
  imports: [UiCardComponent],
  templateUrl: './footer-content.component.html',
  styleUrl: './footer-content.component.scss',
})
export class FooterContentComponent {
  public list: Item[] = [
    {
      name: 'GitHub',
      link: 'https://github.com/astrotrain55',
    },
    {
      name: 'npmjs',
      link: 'https://www.npmjs.com/~astrotrain',
    },
    {
      name: 'Telegram',
      link: 'https://t.me/valentin_fatherland',
    },
    {
      name: 'LinkedIn',
      link: 'https://www.linkedin.com/in/valentin-zolotov/',
    },
  ];
}

<app-ui-card>
  <div class="footer-content">
    <ul class="footer-content__contacts">
      <li>
        <a href="https://github.com/astrotrain55" target="_blank">GitHub</a>
      </li>
      <li>
        <a href="https://www.npmjs.com/~astrotrain" target="_blank">npmjs</a>
      </li>
      <li>
        <a href="https://t.me/valentin_fatherland" target="_blank">Telegram</a>
      </li>
      <li>
        <a href="https://www.linkedin.com/in/valentin-zolotov/" target="_blank">LinkedIn</a>
      </li>
    </ul>
    <img src="assets/qr-code.gif" alt="Контакты" />
  </div>
</app-ui-card>

// src/components/layout/FooterContent.vue
<template>
  <app-card class="footer-content">
    <ul class="footer-content__contacts">
      <li>
        <a href="https://github.com/astrotrain55" target="_blank">GitHub</a>
      </li>
      <li>
        <a href="https://www.npmjs.com/~astrotrain" target="_blank">npmjs</a>
      </li>
      <li>
        <a href="https://t.me/valentin_fatherland" target="_blank">Telegram</a>
      </li>
    </ul>
    <img src="@/assets/qr-code.gif" alt="Контакты">
  </app-card>
</template>

<script>
import AppCard from '../ui/Card.vue';

export default {
  components: {
    AppCard,
  },
  name: 'footer-content',
};
</script>

<style lang="stylus">
.footer-content
  display flex
  justify-content space-between
  align-items center
  margin-bottom 10px
  &__contacts
    flex-grow 1
    list-style-type none
    padding-left 0
</style>
