// src/app/components/tags-cloud/tags-cloud.component.ts
import { Component, EventEmitter, Input, Output } from '@angular/core';
import { UiCardComponent } from '../ui/ui-card/ui-card.component';
import type { TypeTag } from '../../../projects';

@Component({
  selector: 'app-tags-cloud',
  standalone: true,
  imports: [UiCardComponent],
  templateUrl: './tags-cloud.component.html',
  styleUrl: './tags-cloud.component.scss',
})
export class TagsCloudComponent {
  @Input() public tags: (TypeTag | 'all')[] = [];
  @Input({ required: true }) public activeTag: TypeTag | 'all';
  @Input() public isHomePage: boolean = false;
  @Output() public visible: EventEmitter<TypeTag | 'all'> = new EventEmitter<
    TypeTag | 'all'
  >();

  onVisible(tag: TypeTag | 'all') {
    this.visible.emit(tag);
  }

  get sortedTags(): (TypeTag | 'all')[] {
    const sortedTags = this.tags
      .filter((tag) => tag !== 'all')
      .sort((a, b) => {
        if (a < b) return -1;
        if (a > b) return 1;
        return 0;
      });

    return this.isHomePage ? ['all', ...sortedTags] : sortedTags;
  }
}

<div class="tags-cloud">
  @if (isHomePage) {
    <app-ui-card>
      <h2 class="tags-cloud__title">Облако тегов</h2>
      <div class="tags-cloud__list">
        @for (tag of sortedTags; track tag) {
          <a
            href="#"
            class="tags-cloud__tag"
            [ngClass]="{ active: activeTag === tag }"
            (click)="onVisible(tag)"
          >
            @if (tag === 'all') {
              <span>Все проекты</span>
            } @else {
              <span>#{{ tag }}</span>
            }
          </a>
        }
      </div>
    </app-ui-card>
  } @else {
    <app-ui-card>
      <h2 class="tags-cloud__title">Теги</h2>
      <div class="tags-cloud__list">
        @for (tag of sortedTags; track tag) {
          <div class="tags-cloud__tag">
            <span>#{{ tag }}</span>
          </div>
        }
      </div>
    </app-ui-card>
  }
</div>

// src/components/layout/TagsCloud.vue
<template>
  <div class="tags-cloud">
    <app-card v-if="isHomePage">
      <h2 class="tags-cloud__title">Облако тегов</h2>
      <div class="tags-cloud__list">
        <a
          v-for="tag in sortedTags"
          :key="tag"
          href="#"
          class="tags-cloud__tag"
          :class="{ active: activeTag === tag }"
          @click.prevent="$emit('visible', tag)"
        >
          <span v-if="tag === 'all'">Все проекты</span>
          <span v-else>#{{ tag }}</span>
        </a>
      </div>
    </app-card>
    <app-card v-else>
      <h2 class="tags-cloud__title">Теги</h2>
      <div class="tags-cloud__list">
        <div
          v-for="tag in sortedTags"
          :key="tag"
          class="tags-cloud__tag"
        >
          <span>#{{ tag }}</span>
        </div>
      </div>
    </app-card>
  </div>
</template>

<script>
import AppCard from '../ui/Card.vue';

export default {
  computed: {
    isHomePage() {
      return this.$route.name === 'home';
    },
    sortedTags() {
      const sortedTags = this.tags
        .filter((tag) => tag !== 'all')
        .sort((a, b) => {
          if (a < b) return -1;
          if (a > b) return 1;
          return 0;
        });

      return this.isHomePage ? ['all', ...sortedTags] : sortedTags;
    },
  },
  props: {
    tags: {
      type: Array,
      default: () => [],
    },
    activeTag: {
      type: String,
      default: '',
    },
  },
  emits: ['visible'],
  components: {
    AppCard,
  },
  name: 'tags-cloud',
};
</script>

<style lang="stylus">
.tags-cloud
  &__title
    color #92eaff
    font-size 18px
    margin 0
  &__list
    margin-top 5px
  &__tag
    display inline-block
    text-decoration none
    color currentColor
    margin-right 10px
    &.active
      color #c44ee4
</style>
