// src/app/components/picture-card/picture-card.component.ts
import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-picture-card',
  imports: [],
  templateUrl: './picture-card.component.html',
  styleUrl: './picture-card.component.scss',
})
export class PictureCardComponent {
  @Input({ required: true }) public image!: string;
  @Input({ required: true }) public description!: string;
}

<div class="picture-card">
  <img
    class="picture-card__image"
    [ngSrc]="image().src"
    [width]="image().width"
    [height]="image().height"
    [alt]="image().title"
  />
  <h2 class="picture-card__description">{{ image().title }}</h2>
</div>

// src/components/multimedia/PictureCard.vue
<template>
  <div class="picture-card">
    <img class="picture-card__image" :src="image" :alt="description">
    <h2 class="picture-card__description">{{ description }}</h2>
  </div>
</template>

<script>
export default {
  props: {
    image: {
      type: String,
      required: true,
    },
    description: {
      type: String,
      default: '',
    },
  },
  name: 'picture-card',
};
</script>

<style lang="stylus">
.picture-card
  &__image
    width 100%
    max-width 100%
  &__description
    text-align center
    font-size inherit
    margin 5px 0 0
</style>
